Im terrible at math, but I tried
Cole-Allen/rc0821-code-solutions pull request #134
Opened 2021-11-15 23:31 UTC by Cole-Allen

![image](https://user-images.githubusercontent.com/56735362/141869090-45e5be28-a949-4d39-9e93-30029d557fa2.png)

2021-11-15 23:47 UTC, scbowler requested changes
Off to a good start but some updates needed. Let me know if you have any questions

2021-11-15 23:47 UTC, scbowler commented on big-o-notation/big-o.js
> +      unique[unique.length] = word; // n * n = O(n^2)
These would still just be `Operations * n` so `O(n)`

2021-11-15 23:47 UTC, scbowler commented on big-o-notation/big-o.js
> +} // Big O Notation for uniqueLinear: O(n^2)
This function has an `O(n)`

2021-11-15 23:47 UTC, scbowler commented on big-o-notation/big-o.js
> +      let c = 0;                    // 1 * 1 = O(1)
This line will happen once for every iteration of the outer loop so it will be `O(n)`

2021-11-15 23:47 UTC, scbowler commented on big-o-notation/big-o.js
> +    if (isUnique) {                 // 1 * 1 = O(1)
This is still part of the outer loop so will be `O(n)`

2021-11-16 00:19 UTC, scbowler requested changes
Looking much better, just need some updates with the inner loop in the second function. I think I missed that in the first review, so my fault.

2021-11-16 00:19 UTC, scbowler commented on big-o-notation/big-o.js
> +      }
Because these are in an inner loop they would be `O(n^2)`, my apologies I think I missed that on the first review.

2021-11-16 00:22 UTC, Cole-Allen commented
Its hard for me to visualize this one! Im def gonna take some time to study it more

2021-11-16 00:28 UTC, scbowler approved these changes
Great job implementing the feedback, looks good! 👍

2021-11-16 00:28 UTC, merged